=>(Idle)-up->(MovingUp)
(Idle)-down->(MovingDown)
(MovingUp)-stop->[Stopped]
(MovingDown)-stop->[Stopped]
[Stopped]-open->[Open]
[Open]-close->[Idle]
(Idle)-init->(Idle)
(MovingUp)-init->(MovingUp)
(MovingDown)-init->(MovingDown)
[Stopped]-init->[Stopped]
(MovingUp)-up->(Idle)
(MovingDown)-down->(Idle)
